orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@1.1.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          context: fuse-identity-dev
          create-repo: false
          dockerfile: Dockerfile
          path: ./services/dummyuserservice
          profile-name: CircleCI
          region: AWS_REGION
          repo: amido-test
          tag: 'latest,<< pipeline.git.revision >>'
      - deploy-dev:
          steps:
            - run:
                name: Deploy
                command: |
                  aws ecs register-task-definition --task-definition task.json

          