version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@1.1.0

jobs: 
  build_and_push_image:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          context: fuse-identity-dev
          create-repo: false
          dockerfile: Dockerfile
          path: ./services/dummyuserservice
          profile-name: CircleCI
          region: AWS_REGION
          repo: amido-test
          tag: 'latest,<< pipeline.git.revision >>'
  deploy: 
    steps:
      - checkout
      - run:
        name: Deploy Fargate task and service
        command: |
          aws ecs register-task-definition --cli-input-json file://.dummyuserservice/ecs/task.json
          aws ecs create-service --cli-input-json file://.dummyuserservice/ecs/service.json

          