version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
      RUN apt-get update && apt-get install -y \
      python3.4 \
      python3-pip

      RUN pip install awscli
        #  echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
        #  docker run -d --name db company/proprietary-db:1.2.3

     # build the application image
     - run: docker build -t company/app:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push company/app:$CIRCLE_BRANCH