version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0
jobs:
 build:
   machine: true
   steps:
     - checkout
     # build the application image
     - run: docker build -t company/app:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push company/app:$CIRCLE_BRANCH